# Generated by Django 2.1.5 on 2019-01-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawfile',
            name='file_law',
            field=models.FileField(upload_to='srv/sites/media/', verbose_name='Arquivo'),
        ),
    ]
