# Generated by Django 2.1.5 on 2019-01-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0003_auto_20190107_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawfile',
            name='file_law',
            field=models.FileField(upload_to='media/', verbose_name='Arquivo'),
        ),
    ]
