# Generated by Django 2.1.5 on 2019-01-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0004_auto_20190107_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawfile',
            name='file_law',
            field=models.FileField(upload_to='', verbose_name='Arquivo'),
        ),
    ]
